# Generated by Django 5.2.1 on 2025-05-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSINTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('ports', models.JSONField()),
                ('whois', models.TextField()),
                ('dns', models.JSONField()),
                ('dorks', models.JSONField()),
                ('passive_osint', models.JSONField()),
                ('analysis_summary', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
